language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run test
- npm run build
deploy:
  provider: heroku
  app: robofr
  local_dir: build
  api_key:
    secure: s0LHy/dxbWE1MsJ3ye79mTfnjjJaE/f8oDvutkUukQACQgciw7X+050aLa4kCsJ9Mm+86qcyIDCoWx4p02jH1S9lr9o6iNLIyH1y+iSQO4ratT5nL5A5Ot91FcZ/OKxBtd7aFI3pEVTM/VlNVdzSe60kSpr0cYHKi0SXAYSPP/OGQkpL0vMuEbtZdzU9ISrpejBKGw987ebmrOikYKo/QmuE7l4IOPjUPBKsEBQCLAaMkURYdw/h4sZ9v1z/0ZcExYL/XNM5u7MOz4f3rb6fOa4xwinAPfsW90NVj4e+l38/FcfrC78ZsgKrlTU5vPXVWtZFchKbNCqA5JM7cKo+fpIXeNwD4aF0fcBKTIQ3LkR4W/HwcY3q/uofwTOFMuCdQU6FudLfOYInfjOKzdCeKhwGgh81XSGRi/Nfg6HshRg4DXGsrsw5SQPx9xD8Ddp7uQY4IBg2eMdcnh6AbJpAKkHtGsCMyNbQjU072Re8uVohevKyQcwOmLAM4F1Y/VleXhIF8uwTV/QLn+qfpie0rdS+PWCG89yrHF40FbLJwlp1GCasDKEDk3t+4eD1jI4FJsC4MSxcoq/nWVTmatqrUvUHSd1Y9h5GdhD9IqkmMD6pPbqY8K7HT5Mz9ro46q9xI3HCxp+gDMiFLqdaepfKRcm+ltBs04wcGoNV0kI7dnY=
