
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run-script test
  - npm run-script build

#deploy:
  #provider: heroku
  #app: robofr
  #api_key:
    #secure: <your_secure_key>