language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run test
- npm run build
deploy:
  provider: heroku
  app: robofr
  local_dir: build
  api_key:
    secure: hWejOdxy1yCTV6blpzcUOpEUhON1W6I0fxfLLS4nO8dDlGKJGRcewcKfmRp7MBCsg10baJQJ9N/TPXzqbWZjAN6PiWJ59W1ZSh1iIySRp9YBWn1U/rlb6mSsqd7eBdAQbDisdLxAgbCV3EM30nvxufjBa2a1K90tFSmUibBwjIF2ecWDtc3CGkfcZEaZ7AxGiKMCRLcZsdRyySNrOeYR3f2efJ2WD1ayTyB8Qh/Z6ArSkRokQgtEIFZyeqh7c1hE5Fu65WISG+5qTT3tmFCTZMBeR8opWJdy4KhMya9jndtbHEg/PaA03IjEheMmg3d+6+0OTBQyT0y4BSIo3OjBOX0OeRFP1vwMO2tyRrKcsLkpeasJlS8A/gHPk0H8AXEPWDLDu92j7EcBqlG+qkcwkQbqTsRJlAkPUUVl71fOYtiWkYKzZQAn4iGNzgCClEjERNMzOHDUQDm5CCsxV3gapeAZTunxEElrDdFZC1yjWrUXnGPBO03YnlqjVIGrbidRRj4A73qKWa1DVS5MCeyPn1s1877u4Shg7Xshl6UCtQ0IOgFIdS079LdJ3TSIWRLIWwm0NhNI02XkfrLnJQusFcYofgoxJ8+XMkHtcRwpm8dXV9IZ7FiPslKilg4j5Jv6gU2z7Pv+EHWbP+w9j8s1GfXf986DJHWmeXkbWuRSRVY=
