
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run build

deploy:
  provider: heroku
  app: robofr
  api_key:
    secure: FmI9DdsciMV3lsUIHXtgWlXCG5GidBd5E6eKi5pAaPFJsOc4XoAmPD/FhcDAtRwj+2Blsx4GAX4QRliOxm8xpe3x+nxhwTWLORTnNl8F1xnXBgysJewdjuTO7Ukxqb5vAM0ksYwuRy8sJPRABrNil31ruec/6Mmv05g6VIytMnB1bo4xseRTjTECN+7voWccnBo8EzidpyBHXCXPoJ5DwEVYcTKuVfqqmZKT498JpTxAJ8FJIKrIehTwburjxmM3t5VtiiXFP5vL8zthsyPuTWBIcQg462JpKtFEPZd6HXSd08UWvRNVY79CEKBxZimWSYl2MeYTh5w8ZKxDho4VUlnIjZTnmzwL4qzwSOq/5t+eC9K75IgIlqPnNWBCAkl7vSr5WotOlWDOOiqDmPlEyS3e6EEpLMudnk8nBbMr5JlI8S9z1r4QBAQaKa8E5v8ZI7Vlll5WqVTNISz6J2aqXVa4aktKSKQlD6Q+VslXZcbT7U00e62wBbyV8nSjsEd88CflcfJvi4+b3Otb/kC9/iLa276Vf7+EmdZsG9M9l41qq9G1S2fpAAkJAH24tvgFJMUJ4WzdzueKzWXjwn+nm6D74BTsbDJ6dgALBRR8lyXLdBUgLdwZmAIxhFc7t51tC5S2utI9/URZhDqb+XjACyb3a0TmL2o0de1sTBTUyzw=